# Generated by Django 6.0 on 2025-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('cne', models.CharField(max_length=20, unique=True)),
                ('adresse', models.CharField(max_length=200)),
                ('note_1ere', models.FloatField()),
                ('note_2eme', models.FloatField()),
                ('mention', models.CharField(max_length=50)),
            ],
        ),
    ]
